// <auto-generated />
using System;
using KachaowAuto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KachaowAuto.Data.Migrations
{
    [DbContext(typeof(KachaowAutoDbContext))]
    [Migration("20260403083736_SeedPartImages")]
    partial class SeedPartImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KachaowAuto.Data.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("AppointmentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AppointmentStatusId");

                    b.HasIndex("CarId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.AppointmentMechanic", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId", "MechanicId");

                    b.HasIndex("MechanicId");

                    b.ToTable("AppointmentMechanics");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.AppointmentPart", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPriceAtTime")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AppointmentId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("AppointmentParts");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.AppointmentStatus", b =>
                {
                    b.Property<int>("AppointmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentStatusId");

                    b.ToTable("AppointmentStatuses");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.BodyType", b =>
                {
                    b.Property<int>("BodyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BodyTypeId");

                    b.ToTable("BodyTypes");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.EngineType", b =>
                {
                    b.Property<int>("EngineTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EngineTypeId");

                    b.ToTable("EngineTypes");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("EngineTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EngineVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ModelId");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("EngineTypeId");

                    b.HasIndex("BrandId", "ModelName", "EngineTypeId", "EngineVolume", "HorsePower", "BodyTypeId")
                        .IsUnique();

                    b.ToTable("Models");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PartCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PartId");

                    b.HasIndex("PartCategoryId");

                    b.HasIndex("Manufacturer", "PartNumber")
                        .IsUnique()
                        .HasFilter("[Manufacturer] IS NOT NULL AND [PartNumber] IS NOT NULL");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.PartCategory", b =>
                {
                    b.Property<int>("PartCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartCategoryId");

                    b.ToTable("PartCategories");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.PartImage", b =>
                {
                    b.Property<int>("PartImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartImageId");

                    b.HasIndex("PartId");

                    b.ToTable("PartImages");

                    b.HasData(
                        new
                        {
                            PartImageId = 1,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203068/kachaowauto/parts/rxdv9gqcsp49mzwnr8fm.jpg",
                            PartId = 46
                        },
                        new
                        {
                            PartImageId = 2,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203091/kachaowauto/parts/dyaie8c7ynikcuuiiqej.jpg",
                            PartId = 31
                        },
                        new
                        {
                            PartImageId = 3,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203105/kachaowauto/parts/thsbcczibnh8spsonmun.jpg",
                            PartId = 17
                        },
                        new
                        {
                            PartImageId = 4,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203119/kachaowauto/parts/yithggzz3o2zkj5u9hnx.jpg",
                            PartId = 38
                        },
                        new
                        {
                            PartImageId = 5,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203132/kachaowauto/parts/vndxtrtn3esyyjv7jhzf.jpg",
                            PartId = 52
                        },
                        new
                        {
                            PartImageId = 6,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203146/kachaowauto/parts/ht6zvgispnz7boxh4wgu.jpg",
                            PartId = 57
                        },
                        new
                        {
                            PartImageId = 7,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203160/kachaowauto/parts/sncuh48velbvyklkdq5v.jpg",
                            PartId = 53
                        },
                        new
                        {
                            PartImageId = 8,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203178/kachaowauto/parts/tvmrxpwggen9jgknoslf.jpg",
                            PartId = 18
                        },
                        new
                        {
                            PartImageId = 9,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203195/kachaowauto/parts/bujpr6ehhp0pbuh30ms9.webp",
                            PartId = 35
                        },
                        new
                        {
                            PartImageId = 10,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203217/kachaowauto/parts/jdxc2llawr96q6ql5mdq.jpg",
                            PartId = 36
                        },
                        new
                        {
                            PartImageId = 11,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203238/kachaowauto/parts/bfxmv7swtnw6w9erxcr9.jpg",
                            PartId = 3
                        },
                        new
                        {
                            PartImageId = 12,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203272/kachaowauto/parts/zlts30rzbgs89u2ccud7.png",
                            PartId = 41
                        },
                        new
                        {
                            PartImageId = 13,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203292/kachaowauto/parts/xt81fregkhoych98wyzp.jpg",
                            PartId = 39
                        },
                        new
                        {
                            PartImageId = 14,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203308/kachaowauto/parts/qkfyhgtat87yugbepy2a.jpg",
                            PartId = 33
                        },
                        new
                        {
                            PartImageId = 15,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203322/kachaowauto/parts/jeljogguchewmrbnaasz.jpg",
                            PartId = 24
                        },
                        new
                        {
                            PartImageId = 16,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203343/kachaowauto/parts/nwkaczxwxkvxk5suavih.jpg",
                            PartId = 62
                        },
                        new
                        {
                            PartImageId = 17,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203361/kachaowauto/parts/vumoqfreegd1hqbx0has.jpg",
                            PartId = 13
                        },
                        new
                        {
                            PartImageId = 18,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203382/kachaowauto/parts/rn75chixkuglku9vpxdl.jpg",
                            PartId = 5
                        },
                        new
                        {
                            PartImageId = 19,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203404/kachaowauto/parts/dmzvjdiumrrtr9gwirrg.png",
                            PartId = 32
                        },
                        new
                        {
                            PartImageId = 20,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203420/kachaowauto/parts/nlrh5syefrsisrprwtjg.jpg",
                            PartId = 6
                        },
                        new
                        {
                            PartImageId = 21,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203455/kachaowauto/parts/cdcnkcn66hmiahydsa6g.jpg",
                            PartId = 42
                        },
                        new
                        {
                            PartImageId = 22,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203471/kachaowauto/parts/ssmujpnktrnwlumsiwdf.jpg",
                            PartId = 47
                        },
                        new
                        {
                            PartImageId = 23,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203484/kachaowauto/parts/y2xwug8ei0bagohlmzih.jpg",
                            PartId = 10
                        },
                        new
                        {
                            PartImageId = 24,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203501/kachaowauto/parts/ji3y6ckpqvkx0ncdeckb.jpg",
                            PartId = 22
                        },
                        new
                        {
                            PartImageId = 25,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203517/kachaowauto/parts/wsdyppcwpq5qnhryzpep.jpg",
                            PartId = 11
                        },
                        new
                        {
                            PartImageId = 26,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203530/kachaowauto/parts/dijymhgyehpdynxtxnf4.jpg",
                            PartId = 65
                        },
                        new
                        {
                            PartImageId = 27,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203546/kachaowauto/parts/ouwvhhzwqoecfgzaqbcm.webp",
                            PartId = 20
                        },
                        new
                        {
                            PartImageId = 28,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203563/kachaowauto/parts/ipfbfxodv2mzj1h4ehao.jpg",
                            PartId = 40
                        },
                        new
                        {
                            PartImageId = 29,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203578/kachaowauto/parts/ytthk46e5d3cbt7b9akx.jpg",
                            PartId = 23
                        },
                        new
                        {
                            PartImageId = 30,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203593/kachaowauto/parts/z8rvp2ms7ovhacwzmayy.jpg",
                            PartId = 63
                        },
                        new
                        {
                            PartImageId = 31,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203612/kachaowauto/parts/ukzaersts5ipw470bi4h.jpg",
                            PartId = 72
                        },
                        new
                        {
                            PartImageId = 32,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203627/kachaowauto/parts/ixprjnnvizvf4bvgnlme.jpg",
                            PartId = 69
                        },
                        new
                        {
                            PartImageId = 33,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203644/kachaowauto/parts/t25efpowdpqqkxkqwood.jpg",
                            PartId = 1
                        },
                        new
                        {
                            PartImageId = 34,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203689/kachaowauto/parts/y8f3sgbhfuvjfcdfpjcd.jpg",
                            PartId = 64
                        },
                        new
                        {
                            PartImageId = 35,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203706/kachaowauto/parts/pdbutiihcffewgcdom4v.jpg",
                            PartId = 66
                        },
                        new
                        {
                            PartImageId = 36,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203723/kachaowauto/parts/wjdtqluh76k393pbxnyn.png",
                            PartId = 4
                        },
                        new
                        {
                            PartImageId = 37,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203738/kachaowauto/parts/dv2p6cqx1hg6i9qjw2tq.jpg",
                            PartId = 51
                        },
                        new
                        {
                            PartImageId = 38,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203753/kachaowauto/parts/dfh1d5qsif2tkmsjkpza.jpg",
                            PartId = 50
                        },
                        new
                        {
                            PartImageId = 39,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203768/kachaowauto/parts/oo44aglswf9a2cmdyj3m.jpg",
                            PartId = 49
                        },
                        new
                        {
                            PartImageId = 40,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203785/kachaowauto/parts/yt3ymqwxtihnib6ifprt.webp",
                            PartId = 54
                        },
                        new
                        {
                            PartImageId = 41,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203799/kachaowauto/parts/t6gcjntghjigyip1m69v.jpg",
                            PartId = 71
                        },
                        new
                        {
                            PartImageId = 42,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203815/kachaowauto/parts/yenwkg39tofq4hk81grd.jpg",
                            PartId = 14
                        },
                        new
                        {
                            PartImageId = 43,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203831/kachaowauto/parts/qmyxyichuxdtilwvgvlq.jpg",
                            PartId = 45
                        },
                        new
                        {
                            PartImageId = 44,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203849/kachaowauto/parts/j8oiuzmfyyesv1fzug8t.jpg",
                            PartId = 67
                        },
                        new
                        {
                            PartImageId = 45,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203865/kachaowauto/parts/xccjb68lzprsfwvlqeqb.jpg",
                            PartId = 34
                        },
                        new
                        {
                            PartImageId = 46,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203879/kachaowauto/parts/rkj5jzvop0lwdfxiuysb.webp",
                            PartId = 44
                        },
                        new
                        {
                            PartImageId = 47,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203893/kachaowauto/parts/siebcpnmhkhnymukondx.jpg",
                            PartId = 27
                        },
                        new
                        {
                            PartImageId = 48,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203907/kachaowauto/parts/pdfgoupg7g27gqnhzkvg.jpg",
                            PartId = 37
                        },
                        new
                        {
                            PartImageId = 49,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203919/kachaowauto/parts/qrvj9ozdxypwclm4eg1l.jpg",
                            PartId = 21
                        },
                        new
                        {
                            PartImageId = 50,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203940/kachaowauto/parts/cdcpexft9oh6udsajtaj.jpg",
                            PartId = 48
                        },
                        new
                        {
                            PartImageId = 51,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203953/kachaowauto/parts/g0xmmbicapjshtspmlwd.jpg",
                            PartId = 26
                        },
                        new
                        {
                            PartImageId = 52,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203966/kachaowauto/parts/nfeadizk6x4hhwc2whow.jpg",
                            PartId = 19
                        },
                        new
                        {
                            PartImageId = 53,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775203983/kachaowauto/parts/re5htadyrnwksvbmbqsb.jpg",
                            PartId = 9
                        },
                        new
                        {
                            PartImageId = 54,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204051/kachaowauto/parts/ult6oomfcv3obgzsl3vk.jpg",
                            PartId = 28
                        },
                        new
                        {
                            PartImageId = 55,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204072/kachaowauto/parts/xllkggxe8ew0kj8fithj.webp",
                            PartId = 2
                        },
                        new
                        {
                            PartImageId = 56,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204090/kachaowauto/parts/cbtdb5xy5uvigtpclko0.webp",
                            PartId = 61
                        },
                        new
                        {
                            PartImageId = 57,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204107/kachaowauto/parts/j5jah8qey83t6sv4gobn.jpg",
                            PartId = 43
                        },
                        new
                        {
                            PartImageId = 58,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204124/kachaowauto/parts/i7m7obk1znldiuuas7ug.jpg",
                            PartId = 55
                        },
                        new
                        {
                            PartImageId = 59,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204141/kachaowauto/parts/kfxp6ovjfse2nui00u0f.jpg",
                            PartId = 56
                        },
                        new
                        {
                            PartImageId = 60,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204154/kachaowauto/parts/s8ntegg3rijw3jc7cll4.jpg",
                            PartId = 8
                        },
                        new
                        {
                            PartImageId = 61,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204166/kachaowauto/parts/z8kqhc1wabjcib69unga.jpg",
                            PartId = 68
                        },
                        new
                        {
                            PartImageId = 62,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204177/kachaowauto/parts/kaz5x9yhzdjet69tbqm0.jpg",
                            PartId = 29
                        },
                        new
                        {
                            PartImageId = 63,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204190/kachaowauto/parts/owhxlxurctitks4idvyt.jpg",
                            PartId = 7
                        },
                        new
                        {
                            PartImageId = 64,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204206/kachaowauto/parts/s98imtmuiemnofk76xhc.webp",
                            PartId = 16
                        },
                        new
                        {
                            PartImageId = 65,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204218/kachaowauto/parts/fwohy27jwr4pyryxbulm.jpg",
                            PartId = 15
                        },
                        new
                        {
                            PartImageId = 66,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204233/kachaowauto/parts/mf080slgwwvxnqpgi2pl.jpg",
                            PartId = 25
                        },
                        new
                        {
                            PartImageId = 67,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204244/kachaowauto/parts/jyzsutg9byobfgdrfowt.jpg",
                            PartId = 60
                        },
                        new
                        {
                            PartImageId = 68,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204257/kachaowauto/parts/uajxfhby6rmd7sbz0j1m.jpg",
                            PartId = 59
                        },
                        new
                        {
                            PartImageId = 69,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204277/kachaowauto/parts/eimtbih0nu4qpnzdqmsk.png",
                            PartId = 30
                        },
                        new
                        {
                            PartImageId = 70,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204292/kachaowauto/parts/rtxlaqkrt64ozn3uk7ki.jpg",
                            PartId = 12
                        },
                        new
                        {
                            PartImageId = 71,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204307/kachaowauto/parts/e9pws6zcdlensddztbxz.jpg",
                            PartId = 70
                        },
                        new
                        {
                            PartImageId = 72,
                            ImageUrl = "https://res.cloudinary.com/dlfzltmrr/image/upload/v1775204324/kachaowauto/parts/dmle30bgcgxbm5pjer9t.webp",
                            PartId = 58
                        });
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.PartRequest", b =>
                {
                    b.Property<int>("PartRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartRequestId"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PartRequestId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("PartId");

                    b.ToTable("PartRequests");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PriceFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceTo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.ServiceCategory", b =>
                {
                    b.Property<int>("ServiceCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceCategoryId");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Workshop", b =>
                {
                    b.Property<int>("WorkshopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkshopId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("WorkshopId");

                    b.HasIndex("RegionId", "City");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.WorkshopService", b =>
                {
                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("WorkshopId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("WorkshopServices");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Appointment", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.AppointmentStatus", "Status")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.Car", "Car")
                        .WithMany("Appointments")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.Workshop", "Workshop")
                        .WithMany("Appointments")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Service");

                    b.Navigation("Status");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.AppointmentMechanic", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.Appointment", "Appointment")
                        .WithMany("AppointmentMechanics")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.ApplicationUser", "Mechanic")
                        .WithMany("AppointmentMechanics")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.AppointmentPart", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.Appointment", "Appointment")
                        .WithMany("AppointmentParts")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.Part", "Part")
                        .WithMany("AppointmentParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Car", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.ApplicationUser", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Model", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.BodyType", "BodyType")
                        .WithMany("Models")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.EngineType", "EngineType")
                        .WithMany("Models")
                        .HasForeignKey("EngineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("Brand");

                    b.Navigation("EngineType");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Part", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.PartCategory", "Category")
                        .WithMany("Parts")
                        .HasForeignKey("PartCategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.PartImage", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.Part", "Part")
                        .WithMany("Images")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.PartRequest", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.ApplicationUser", "Mechanic")
                        .WithMany("PartRequests")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.Part", "Part")
                        .WithMany("PartRequests")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mechanic");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Service", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Workshop", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.Region", "Region")
                        .WithMany("Workshops")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.WorkshopService", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.Service", "Service")
                        .WithMany("WorkshopServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.Workshop", "Workshop")
                        .WithMany("WorkshopServices")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KachaowAuto.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("KachaowAuto.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("AppointmentMechanics");

                    b.Navigation("Cars");

                    b.Navigation("PartRequests");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentMechanics");

                    b.Navigation("AppointmentParts");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.AppointmentStatus", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.BodyType", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Car", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.EngineType", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Model", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Part", b =>
                {
                    b.Navigation("AppointmentParts");

                    b.Navigation("Images");

                    b.Navigation("PartRequests");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.PartCategory", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Region", b =>
                {
                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("WorkshopServices");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("KachaowAuto.Data.Models.Workshop", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("WorkshopServices");
                });
#pragma warning restore 612, 618
        }
    }
}
